#server:
# port: 8761
#自定义地址名称
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#client自我保护，开发环境关掉，防止调用时是关的而server显示是开的
  server:
    enable-self-preservation: false
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wukopass/config.git
logging:
  level:
    root: info
  file: logs/server.log